- name: Create rclone-serve users
  vars:
    dest: "{{ rclone_serve.prefix.config }}/{{ item.htpasswd }}.htpasswd"
    owner: "{{ item.daemon_user|default(rclone_serve.defaults.daemon_user, true) }}"
  loop: "{{ rclone_serve.config|rclone_serve_flatten_htpasswd }}"
  loop_control:
    label: "{{ dest }} username={{ item.username }}"
  htpasswd:
    path: "{{ dest }}"
    owner: "{{ owner }}"
    group: "{{ owner }}"
    mode: 0600
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    crypt_scheme: "{{ item.crypt_scheme }}"
    state: "{{ 'present' if item.password else 'absent' }}"
